from math import *
from main import calcul_rayon_Gauss as Rg
import Conversion
from PyQt5 import QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

class Ui_Form10(object):
    def function(self):
      phi1d=float(self.lineEdit.text())
      phi1m=float(self.lineEdit_2.text())
      phi1s=float(self.lineEdit_3.text())
      lambda_1d=float(self.lineEdit_4.text())
      lambda_1m=float(self.lineEdit_5.text())
      lambda_1s=float(self.lineEdit_6.text())
      A12d=float(self.lineEdit_7.text())
      A12m= float(self.lineEdit_14.text())
      A12s=float(self.lineEdit_15.text())
      d=float(self.lineEdit_19.text())

      phi1 = Conversion.dmstorad(phi1d, phi1m, phi1s)
      lambda_1 = Conversion.dmstorad(lambda_1d, lambda_1m, lambda_1s)
      A12 = Conversion.dmstorad(A12d, A12m, A12s)

      a = 6378249.145
      b = 6356515.0

      sigma12 = d / Rg(a, b)
      print(sigma12)
      # DETERMINATION DE LA LATITUDE DU POINT P2
      An = cos((pi / 2) - phi1) * cos(sigma12) + sin((pi / 2) - phi1) * sin(sigma12) * cos(A12)
      sinPhi2 = sin(phi1) * cos(sigma12) + cos(phi1) * sin(sigma12) * cos(A12)
      phi2d = asin(sinPhi2)
      (phi2d_d,phi2d_m,phi2d_s)=Conversion.radtodms(phi2d)

      # DETERMINATION DE LA Longitude DU POINT P2
      cot_lambda2 = ((1 / sin(A12)) * ((1 / tan(sigma12)) * sin((pi / 2) - phi1) - cos((pi / 2) - phi1) * cos(A12))) * (
                  180 / pi)
      arcot1 = pi / 2 - atan(cot_lambda2)
      lambda_2 = lambda_1 + arcot1
      (lambda_2d, lambda_2m, lambda_2s) = Conversion.radtodms(lambda_2)
      # DETERMINATION DE L'AZIMUT DU POINT P2
      #A21 = 1 / atan(1 / sin(A12) * (cos(sigma12) * cos(A12) - tan(phi1) * sin(sigma12))) * 180 / pi
      cot_A21 = 1 / sin(A12) * (cos(sigma12) * cos(A12) - tan(phi1) * sin(sigma12))
      arcot2 = pi / 2 - atan(cot_A21)
      A21 = arcot2
      (A21_d,A21_m,A21_s)=Conversion.radtodms(A21)

      self.lineEdit_8.setText(str(phi2d_d))
      self.lineEdit_9.setText(str(phi2d_m))
      self.lineEdit_10.setText(str(phi2d_s))

      self.lineEdit_11.setText(str(lambda_1d))
      self.lineEdit_12.setText(str(lambda_1m))
      self.lineEdit_13.setText(str(lambda_1s))

      self.lineEdit_17.setText(str(A21_d))
      self.lineEdit_18.setText(str(A21_m))
      self.lineEdit_16.setText(str(A21_s))
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(840, 361)
        Form.setStyleSheet(u"background-color: rgb(171, 180, 255);")
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(8, 134, 91, 21))
        font = QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(176, 135, 16, 16))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        self.label_3.setFont(font1)
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(251, 134, 16, 16))
        self.label_4.setFont(font1)
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(330, 134, 16, 16))
        self.label_5.setFont(font1)
        self.pushButton = QPushButton(Form)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(330, 290, 101, 41))
        font2 = QFont()
        font2.setPointSize(9)
        font2.setBold(True)
        self.pushButton.setFont(font2)
        self.pushButton.setStyleSheet(u"\n"
"background-color: rgb(255, 255, 255);")
        self.label_17 = QLabel(Form)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(270, 30, 271, 51))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(True)
        self.label_17.setFont(font3)
        self.label_17.setStyleSheet(u"color: rgb(170, 0, 0);\n"
"color: rgb(0, 0, 127);")
        self.label_24 = QLabel(Form)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(600, 124, 16, 16))
        self.label_11 = QLabel(Form)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(177, 176, 16, 16))
        self.label_11.setFont(font1)
        self.label_13 = QLabel(Form)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(332, 175, 16, 16))
        self.label_13.setFont(font1)
        self.label_12 = QLabel(Form)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(253, 176, 16, 16))
        self.label_12.setFont(font1)
        self.lineEdit_6 = QLineEdit(Form)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(269, 175, 57, 19))
        self.lineEdit_6.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_4 = QLineEdit(Form)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(114, 176, 57, 19))
        self.lineEdit_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_2 = QLineEdit(Form)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(193, 134, 56, 19))
        self.lineEdit_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_10 = QLabel(Form)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(8, 179, 101, 16))
        self.label_10.setFont(font)
        self.lineEdit_3 = QLineEdit(Form)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(269, 134, 57, 19))
        self.lineEdit_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit = QLineEdit(Form)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(114, 133, 57, 20))
        self.lineEdit.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_5 = QLineEdit(Form)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(194, 176, 56, 19))
        self.lineEdit_5.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_14 = QLabel(Form)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(9, 222, 71, 16))
        self.label_14.setFont(font)
        self.lineEdit_8 = QLineEdit(Form)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(532, 129, 71, 19))
        self.lineEdit_8.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_9 = QLineEdit(Form)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(630, 128, 71, 20))
        self.lineEdit_9.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_6 = QLabel(Form)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(820, 130, 16, 16))
        font4 = QFont()
        font4.setPointSize(10)
        self.label_6.setFont(font4)
        self.label_7 = QLabel(Form)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(710, 130, 16, 16))
        self.label_7.setFont(font4)
        self.label_8 = QLabel(Form)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(433, 128, 81, 20))
        font5 = QFont()
        font5.setPointSize(10)
        font5.setBold(False)
        self.label_8.setFont(font5)
        self.label_9 = QLabel(Form)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(610, 130, 16, 16))
        self.lineEdit_10 = QLineEdit(Form)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(720, 129, 91, 19))
        self.lineEdit_10.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_11 = QLineEdit(Form)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(531, 173, 71, 19))
        self.lineEdit_11.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_18 = QLabel(Form)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(610, 170, 16, 16))
        self.label_19 = QLabel(Form)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(708, 170, 16, 16))
        self.label_19.setFont(font4)
        self.label_20 = QLabel(Form)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(432, 174, 91, 20))
        self.label_20.setFont(font5)
        self.lineEdit_12 = QLineEdit(Form)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(630, 170, 71, 19))
        self.lineEdit_12.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_21 = QLabel(Form)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(820, 170, 16, 16))
        self.label_21.setFont(font4)
        self.lineEdit_13 = QLineEdit(Form)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(720, 170, 91, 19))
        self.lineEdit_13.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_7 = QLineEdit(Form)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(114, 220, 57, 19))
        self.lineEdit_7.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_15 = QLabel(Form)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(251, 220, 16, 16))
        self.label_15.setFont(font1)
        self.label_22 = QLabel(Form)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(175, 221, 16, 16))
        self.label_22.setFont(font1)
        self.lineEdit_14 = QLineEdit(Form)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(193, 220, 56, 19))
        self.lineEdit_14.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_15 = QLineEdit(Form)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(270, 220, 57, 19))
        self.lineEdit_15.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_23 = QLabel(Form)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(332, 220, 16, 16))
        self.label_23.setFont(font1)
        self.lineEdit_16 = QLineEdit(Form)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(720, 215, 91, 20))
        self.lineEdit_16.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_16 = QLabel(Form)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(704, 216, 16, 16))
        self.label_16.setFont(font1)
        self.label_27 = QLabel(Form)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(433, 218, 71, 16))
        self.label_27.setFont(font)
        self.lineEdit_17 = QLineEdit(Form)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(531, 216, 71, 20))
        self.lineEdit_17.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_18 = QLineEdit(Form)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.lineEdit_18.setGeometry(QRect(630, 216, 71, 19))
        self.lineEdit_18.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_25 = QLabel(Form)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(610, 218, 16, 16))
        self.label_26 = QLabel(Form)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(817, 218, 16, 16))
        self.label_26.setFont(font4)
        self.label_28 = QLabel(Form)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 260, 141, 16))
        self.label_28.setFont(font)
        self.lineEdit_19 = QLineEdit(Form)
        self.lineEdit_19.setObjectName(u"lineEdit_19")
        self.lineEdit_19.setGeometry(QRect(160, 260, 91, 20))
        self.lineEdit_19.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_29 = QLabel(Form)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(255, 262, 16, 16))
        self.label_29.setFont(font4)

        self.pushButton.clicked.connect(self.function)
        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Latitude de P1", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"\u00b0", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"'", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\"", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"Convertir", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"Probl\u00e8me Direct Sur La Sph\u00e8re", None))
        self.label_24.setText("")
        self.label_11.setText(QCoreApplication.translate("Form", u"\u00b0", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"\"", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"'", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"Longitude de P1", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"Azimut A12", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"\"", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"'", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"Latitude de P2", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"\u00b0", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"\u00b0", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"'", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"Longitude de P2", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"\"", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"'", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"\u00b0", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"\"", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"'", None))
        self.label_27.setText(QCoreApplication.translate("Form", u"Azimut A21", None))
        self.label_25.setText(QCoreApplication.translate("Form", u"\u00b0", None))
        self.label_26.setText(QCoreApplication.translate("Form", u"\"", None))
        self.label_28.setText(QCoreApplication.translate("Form", u"Distance entre P1 et P2", None))
        self.label_29.setText(QCoreApplication.translate("Form", u"m", None))
    # retranslateUi

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form10()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())