
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import Rad
import math

import numpy as np

class Ui_Form1(object):


    def function(self):
        a = 6378249.20
        e_2 = 0.0068034876
        #excentricité au carré
        phi_d = int(self.lineEdit.text())
        phi_m = int(self.lineEdit_2.text())
        phi_s = float(self.lineEdit_3.text())
        Landa_d = int(self.lineEdit_4.text())
        Landa_m = int(self.lineEdit_5.text())
        Landa_s = float(self.lineEdit_6.text())
        h = float(self.lineEdit_7.text())

        phi = Rad.Convertion(phi_d, phi_m, phi_s)
        Landa = Rad.Convertion(Landa_d, Landa_m, Landa_s)
        N = a / (math.sqrt(1 - e_2 * np.sin(phi) ** 2))
        X = (N + h) * np.cos(phi) * np.cos(Landa)
        Y = (N + h) * np.cos(phi) * np.sin(Landa)
        Z = (N * (1 - e_2) + h) * np.sin(phi)
        # return (X, Y, Z)

        self.lineEdit_8.setText(str(X))
        self.lineEdit_10.setText(str(Z))
        self.lineEdit_9.setText(str(Y))




    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(658, 300)
        Form.setStyleSheet(u"background-color: rgb(171, 180, 255);")
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 60, 241, 41))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet(u"color: rgb(0, 0, 127);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(9, 134, 71, 21))
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(False)
        self.label_2.setFont(font1)
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(150, 135, 16, 16))
        self.label_3.setFont(font)
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(225, 134, 16, 16))
        self.label_4.setFont(font)
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(304, 134, 16, 16))
        self.label_5.setFont(font)
        self.label_16 = QLabel(Form)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(452, 60, 241, 41))
        self.label_16.setFont(font)
        self.label_16.setStyleSheet(u"color: rgb(0, 0, 127);\n"
"color: rgb(0, 0, 0);")
        self.pushButton = QPushButton(Form)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(300, 240, 101, 41))
        font2 = QFont()
        font2.setPointSize(9)
        font2.setBold(True)
        self.pushButton.setFont(font2)
        self.pushButton.setStyleSheet(u"\n"
"background-color: rgb(255, 255, 255);")
        self.label_17 = QLabel(Form)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(50, 10, 581, 41))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(True)
        self.label_17.setFont(font3)
        self.label_17.setStyleSheet(u"color: rgb(170, 0, 0);\n"
"color: rgb(0, 0, 127);")
        self.label_23 = QLabel(Form)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(451, 124, 17, 16))
        self.label_23.setFont(font1)
        self.label_25 = QLabel(Form)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(451, 196, 16, 16))
        self.label_25.setFont(font1)
        self.label_24 = QLabel(Form)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(600, 124, 16, 16))
        self.label_26 = QLabel(Form)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(449, 160, 17, 16))
        self.label_26.setFont(font1)
        self.lineEdit_8 = QLineEdit(Form)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(472, 124, 97, 19))
        self.lineEdit_8.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_10 = QLineEdit(Form)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(472, 196, 97, 19))
        self.lineEdit_10.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_10.setReadOnly(False)
        self.lineEdit_9 = QLineEdit(Form)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(472, 160, 97, 19))
        self.lineEdit_9.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_9.setReadOnly(False)
        self.label_11 = QLabel(Form)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(150, 170, 16, 16))
        self.label_11.setFont(font)
        self.label_13 = QLabel(Form)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(305, 170, 16, 16))
        self.label_13.setFont(font)
        self.label_12 = QLabel(Form)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(226, 170, 16, 16))
        self.label_12.setFont(font)
        self.lineEdit_6 = QLineEdit(Form)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(243, 170, 57, 19))
        self.lineEdit_6.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_4 = QLineEdit(Form)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(89, 170, 57, 19))
        self.lineEdit_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_2 = QLineEdit(Form)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(167, 134, 56, 19))
        self.lineEdit_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_10 = QLabel(Form)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(8, 170, 71, 16))
        self.label_10.setFont(font1)
        self.lineEdit_3 = QLineEdit(Form)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(243, 134, 57, 19))
        self.lineEdit_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_7 = QLineEdit(Form)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(89, 206, 57, 19))
        self.lineEdit_7.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit = QLineEdit(Form)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(89, 134, 57, 19))
        self.lineEdit.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_5 = QLineEdit(Form)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(167, 170, 56, 19))
        self.lineEdit_5.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_14 = QLabel(Form)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(9, 206, 61, 16))
        self.label_14.setFont(font1)
        self.label_15 = QLabel(Form)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(151, 207, 30, 16))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(False)
        self.label_15.setFont(font4)
        #self.pushButton.clicked.connect(self.geocart)
        self.pushButton.clicked.connect(self.function)
        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    # setupUi

    def retranslateUi(self,Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label.setText(QCoreApplication.translate("Form", u"Coordonn\u00e9es G\u00e9ographiques ", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Latitude (\u03c6)", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"\u00b0", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"'", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\"", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"Coordonn\u00e9es cart\u00e9siennes ", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"Convertir", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"Transformation des coordonn\u00e9es g\u00e9ographiques aux cordonn\u00e9es cart\u00e9siennes ", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"X ", None))
        self.label_25.setText(QCoreApplication.translate("Form", u"Z", None))
        self.label_24.setText("")
        self.label_26.setText(QCoreApplication.translate("Form", u"Y", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"\u00b0", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"\"", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"'", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"Longitude(\u03bb)", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"Hauteur(h)", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"m", None))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form1()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
